Repository openshift-labs/learn-katacoda, pull requests merged in 2021-06, with the labels that each got.

#1119 pipelines to openshift 4.7
  assets/middleware/pipelines/web-console-settings.png
  middleware/pipelines/01install-op.md
  middleware/pipelines/02new-project.md
  middleware/pipelines/06trigger-pipeline.md
  middleware/pipelines/assets/operator/subscription.yaml
  middleware/pipelines/index.json
  middleware/pipelines/set-env.sh
Labels: Topic: gitOps

#1121 serverless to 4-7
  assets/developing-on-openshift/serverless/01-prepare/04-serverlesssubscription.png
  developing-on-openshift/serverless/00-intro.md
  developing-on-openshift/serverless/01-prepare.md
  developing-on-openshift/serverless/02-serving.md
  developing-on-openshift/serverless/05-scaling.md
  developing-on-openshift/serverless/99-outro.md
  developing-on-openshift/serverless/assets/01-prepare/operator-subscription.yaml
  developing-on-openshift/serverless/env-init.sh
  developing-on-openshift/serverless/index.json
Labels: Topic: Developing on OpenShift, Topic: kNative

#1123 helm to openshfit-4-7
  developing-on-openshift/helm/00-intro.md
  developing-on-openshift/helm/99-outro.md
  developing-on-openshift/helm/index.json
Labels: Topic: Developing on OpenShift

#1135 tkn client missing from "openshift-4-7-client" image
  middleware/pipelines/set-env.sh
Labels: Topic: gitOps

#1143 quarkus content from 4-4 to 4-7
  middleware/middleware-quarkus/getting-started/index.json
  middleware/middleware-quarkus/kafka/index.json
  middleware/middleware-quarkus/monitoring/index.json
  middleware/middleware-quarkus/qute/index.json
  middleware/middleware-quarkus/reactive-sql/index.json
  middleware/middleware-quarkus/spring/index.json
Labels: Topic: Quarkus

#1150 etcd to 4-7
  operatorframework/etcd-operator/finish.md
  operatorframework/etcd-operator/index.json
  operatorframework/etcd-operator/intro.md
  operatorframework/go-operator-podset/index.json
  operatorframework/helm-operator/index.json
  operatorframework/operator-lifecycle-manager/index.json
Labels: Topic: Operators

#1148 Add 2 new courses
  environments/openshift-4-7/client/build/3_op-sdk-setup.sh
  operatorframework-pathway.json
  operatorframework/go-operator-memcached/assets/cache_v1alpha1_memcached.yaml
  operatorframework/go-operator-memcached/assets/images/ansible-op-flow.png
  operatorframework/go-operator-memcached/assets/memcached_controller.go
  operatorframework/go-operator-memcached/assets/memcached_types.go
  operatorframework/go-operator-memcached/env-init.sh
  operatorframework/go-operator-memcached/finish.md
  operatorframework/go-operator-memcached/index.json
  operatorframework/go-operator-memcached/intro.md
  operatorframework/go-operator-memcached/set-env.sh
  operatorframework/go-operator-memcached/step1.md
  operatorframework/go-operator-memcached/step10.md
  operatorframework/go-operator-memcached/step11.md
  operatorframework/go-operator-memcached/step12.md
  operatorframework/go-operator-memcached/step2.md
  operatorframework/go-operator-memcached/step3.md
  operatorframework/go-operator-memcached/step4.md
  operatorframework/go-operator-memcached/step5.md
  operatorframework/go-operator-memcached/step6.md
  operatorframework/go-operator-memcached/step7.md
  operatorframework/go-operator-memcached/step8.md
  operatorframework/go-operator-memcached/step9.md
  operatorframework/helm-operator-memcached/assets/.init.sh
  operatorframework/helm-operator-memcached/assets/charts_v1alpha1_memcached.yaml
  operatorframework/helm-operator-memcached/env-init.sh
  operatorframework/helm-operator-memcached/finish.md
  operatorframework/helm-operator-memcached/index.json
  operatorframework/helm-operator-memcached/intro.md
  operatorframework/helm-operator-memcached/set-env.sh
  operatorframework/helm-operator-memcached/step1.md
  operatorframework/helm-operator-memcached/step2.md
  operatorframework/helm-operator-memcached/step3.md
  operatorframework/helm-operator-memcached/step4.md
  operatorframework/helm-operator-memcached/step5.md
  operatorframework/helm-operator-memcached/step6.md
  operatorframework/helm-operator-memcached/step7.md
Labels: Topic: Operators

#1155 change from 4-5 to 4-7
  operatorframework/go-operator-memcached/index.json
Labels: Topic: Operators

#1145 AI/ML to openshift-47
  ai-machine-learning/thoth-s2i-advise/index.json
  ai-machine-learning/thoth-s2i-provenance/index.json
Labels: Topic: AI / ML

#1144 Kogito to 47
  middleware/middleware-kogito/dmn/index.json
  middleware/middleware-kogito/getting-started/index.json
  middleware/middleware-kogito/optaplanner-knapsack/index.json
  middleware/middleware-kogito/rest-service-integration/index.json
  middleware/middleware-kogito/rules/index.json
  middleware/middleware-kogito/service-task-cdi/index.json
Labels: Topic: Kogito
